// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a placeholder — run `make proto` to regenerate.
package proto

type GetRequest struct {
	Key string
}
type GetResponse struct {
	Key     string
	Value   []byte
	Found   bool
	Version int64
}
type PutRequest struct {
	Key   string
	Value []byte
}
type PutResponse struct {
	Key     string
	Version int64
}
type DeleteRequest struct {
	Key string
}
type DeleteResponse struct {
	Deleted bool
}
type BatchPutRequest struct {
	Entries []*PutRequest
}
type BatchPutResponse struct {
	Count int32
}
type WatchRequest struct {
	Prefix string
}
type WatchEvent struct {
	Key     string
	Value   []byte
	Type    int32
	Version int64
}
type LogEntry struct {
	Index     int64
	Term      int64
	Key       string
	Value     []byte
	Operation string
}
type AppendEntriesRequest struct {
	Term         int64
	LeaderId     string
	PrevLogIndex int64
	PrevLogTerm  int64
	Entries      []*LogEntry
	LeaderCommit int64
}
type AppendEntriesResponse struct {
	Term    int64
	Success bool
}
type RequestVoteRequest struct {
	Term         int64
	CandidateId  string
	LastLogIndex int64
	LastLogTerm  int64
}
type RequestVoteResponse struct {
	Term        int64
	VoteGranted bool
}
